=== nvonaesch/SNIR2/NetBeansProjects/Xml_Dtd_Xsl/Coursxml/public_html/lycee.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT lycee (classe+)>
<!ELEMENT classe (eleve*,prof*)>
<!ELEMENT eleve (nom?,prenom?,age?)>
<!ELEMENT prof (nom?,prenom?,age?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>

<!ATTLIST classe nom CDATA #IMPLIED>

=== nvonaesch/SNIR2/NetBeansProjects/Xml_Dtd_Xsl/Coursxml/public_html/lycee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lycee SYSTEM 'lycee.dtd'>
<?xml-stylesheet href="lycee.xsl" type="text/xsl" ?>
<lycee>
    <classe nom="classe bidon">
        <eleve>
            <nom>Bidochon</nom>
            <prenom>Robert</prenom>
            <age>54</age>
        </eleve>
        <eleve>
            <nom>Galopin</nom>
            <prenom>Raymonde</prenom>
            <age>52</age>
        </eleve>
        <prof>
            <nom>Jack</nom>
            <prenom>Lang</prenom>
            <age>99</age>
        </prof>
    </classe>
</lycee>
